// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH1: typeof import('naive-ui')['NH1']
    NInput: typeof import('naive-ui')['NInput']
    NPageheader: typeof import('naive-ui')['NPageheader']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NPagination: typeof import('naive-ui')['NPagination']
    TodoContent: typeof import('./src/components/todolist/todo-content/index.vue')['default']
    TodoFooter: typeof import('./src/components/todolist/todo-footer/index.vue')['default']
    TodoHeader: typeof import('./src/components/todolist/todo-header/index.vue')['default']
    Todolist: typeof import('./src/components/todolist/index.vue')['default']
  }
}

export { }
